on:
  push:
  pull_request:
  merge_group:

name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v4
    - name: Set up toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Set up Z3
      uses: cda-tum/setup-z3@v1
    - name: Run tests
      run: cargo test
    - name: Run tests and verify with SMT
      run: cargo test --features verify -p prjunnamed-generic

  document:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Set up mdBook
        uses: peaceiris/actions-mdbook@v2
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build the book
        run: mdbook build docs
      - name: Build the API docs
        run: cargo doc --lib --no-deps
      - name: Compile documentation
        run: |
          mkdir output
          cp -r docs/book  output/book
          cp -r target/doc output/api
      - name: Upload documentation archive
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: output/

  publish:
    needs: document
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Download documentation archive
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: output/
      - name: Publish documentation
        if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: output/

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: EmbarkStudios/cargo-deny-action@v2
      with:
        # Must bump above the default of 1.71.0 to accept edition 2024.
        # Kept below 1.85.0 to work around https://github.com/EmbarkStudios/cargo-deny/issues/741
        rust-version: 1.84
